# Generated by Django 4.2.2 on 2023-06-22 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee', models.CharField(max_length=200)),
                ('EmployeeID', models.CharField(max_length=200)),
                ('Firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(choices=[('CEO', 'CEO'), ('HR', 'HR'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Quality Analyst', 'Quality Analyst'), ('BD', 'BD')], max_length=100)),
                ('role', models.CharField(choices=[('Management', 'Management'), ('Wordpress', 'Wordpress'), ('Python', 'Python'), ('UI/UX', 'UI/UX'), ('QA', 'QA')], max_length=20)),
                ('salary', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
