# Generated by Django 4.2.2 on 2023-06-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='role',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Management', 'Management'), ('Wordpress', 'Wordpress'), ('Python', 'Python'), ('UI/UX', 'UI/UX'), ('QA', 'QA')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empapp.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('CEO', 'CEO'), ('HR', 'HR'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Quality Analyst', 'Quality Analyst'), ('BD', 'BD')], max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empapp.employees')),
            ],
        ),
    ]
