# Generated by Django 4.2.2 on 2023-06-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_employee_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_leaves',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee_leaves',
            name='to_date',
            field=models.DateField(),
        ),
    ]
