# Generated by Django 4.2.2 on 2023-06-23 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_alter_employee_leaves_from_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeID',
            new_name='employeeID',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='employees',
            name='des',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empapp.designation'),
        ),
        migrations.AddField(
            model_name='employees',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empapp.role'),
        ),
    ]
