# Generated by Django 4.2.2 on 2023-06-23 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0006_rename_employee_employees_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='des',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='team',
        ),
    ]
