# Generated by Django 4.2.2 on 2023-06-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0008_alter_employees_employeeid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='role',
            new_name='team',
        ),
    ]
